/*
 * mruby_helpers.c - CRuby-API-compatible wrapper functions for mruby
 *
 * This file provides C functions with the SAME names and signatures as CRuby's
 * C API (rb_intern, rb_funcallv, rb_int2inum, etc.). Internally, they use the
 * global konpeito_mrb_state to call the corresponding mruby API functions.
 *
 * This allows the LLVM IR generated by Konpeito to be identical for both
 * CRuby and mruby runtimes — no call-site changes needed.
 *
 * Additionally, mruby macros (mrb_fixnum_value, mrb_nil_value, etc.) cannot be
 * called from LLVM IR, so thin C wrappers are provided for those as well.
 */

#include <mruby.h>
#include <mruby/value.h>
#include <mruby/class.h>
#include <mruby/data.h>
#include <mruby/string.h>
#include <mruby/array.h>
#include <mruby/hash.h>
#include <mruby/proc.h>
#include <mruby/error.h>
#include <mruby/variable.h>
#include <mruby/numeric.h>
#include <mruby/range.h>
#include <string.h>
#include <stdio.h>
#include <stdarg.h>
#include <stdint.h>

/* ================================================================
 * Global mrb_state pointer (set by main() in generated init code)
 * All CRuby-compatible wrappers below use this to access mruby.
 * ================================================================ */

mrb_state *konpeito_mrb_state = NULL;

mrb_state *konpeito_get_mrb_state(void) {
    return konpeito_mrb_state;
}

/* ================================================================
 * Block stack for rb_yield / rb_block_given_p / rb_block_proc
 *
 * mruby requires explicit block values, unlike CRuby's implicit
 * "current block" context. We maintain a stack of block values
 * that wrapper functions push/pop around LLVM function calls.
 * ================================================================ */

#define KONPEITO_MAX_BLOCK_STACK 64
static mrb_value konpeito_block_stack[KONPEITO_MAX_BLOCK_STACK];
static int konpeito_block_stack_depth = 0;

void konpeito_push_block(mrb_value block) {
    if (konpeito_block_stack_depth < KONPEITO_MAX_BLOCK_STACK) {
        konpeito_block_stack[konpeito_block_stack_depth++] = block;
    }
}

void konpeito_pop_block(void) {
    if (konpeito_block_stack_depth > 0) {
        konpeito_block_stack_depth--;
    }
}

static mrb_value konpeito_get_block(void) {
    if (konpeito_block_stack_depth > 0) {
        return konpeito_block_stack[konpeito_block_stack_depth - 1];
    }
    return mrb_nil_value();
}

/* ================================================================
 * mruby constant values (Qnil, Qtrue, Qfalse, Qundef equivalents)
 * These are stored as mrb_value but exposed as uint64_t (VALUE) to
 * match CRuby's convention. Initialized by konpeito_mruby_init_constants().
 * ================================================================ */

/* konpeito_mrb_*_value() helpers for LLVM-generated init function */
mrb_value konpeito_mrb_nil_value(void)   { return mrb_nil_value(); }
mrb_value konpeito_mrb_true_value(void)  { return mrb_true_value(); }
mrb_value konpeito_mrb_false_value(void) { return mrb_false_value(); }
mrb_value konpeito_mrb_undef_value(void) { return mrb_undef_value(); }

/* ================================================================
 * CRuby-compatible API wrappers
 *
 * Each function has the same name and signature as CRuby's C API.
 * In CRuby, VALUE is uint64_t (tagged pointer). In mruby, mrb_value
 * is a struct (or uint64_t with NaN-boxing). We treat them both as
 * uint64_t at the LLVM level since they're the same size.
 * ================================================================ */

/* --- Symbol / Intern --- */

/* CRuby: ID rb_intern(const char *name) */
mrb_sym rb_intern(const char *name) {
    return mrb_intern_cstr(konpeito_mrb_state, name);
}

/* --- Method dispatch --- */

/* CRuby: VALUE rb_funcallv(VALUE recv, ID mid, int argc, const VALUE *argv) */
mrb_value rb_funcallv(mrb_value recv, mrb_sym mid, int argc, const mrb_value *argv) {
    return mrb_funcall_argv(konpeito_mrb_state, recv, mid, argc, argv);
}

/* CRuby: VALUE rb_funcallv_kw(VALUE recv, ID mid, int argc, const VALUE *argv, int kw_splat) */
/* mruby has no keyword args - ignore kw_splat, just call normally */
mrb_value rb_funcallv_kw(mrb_value recv, mrb_sym mid, int argc, const mrb_value *argv, int kw_splat) {
    (void)kw_splat;
    return mrb_funcall_argv(konpeito_mrb_state, recv, mid, argc, argv);
}

/* --- Integer conversion --- */

/* CRuby: VALUE rb_int2inum(long n) */
mrb_value rb_int2inum(int64_t n) {
    return mrb_fixnum_value((mrb_int)n);
}

/* CRuby: long rb_num2long(VALUE v) */
int64_t rb_num2long(mrb_value v) {
    return (int64_t)mrb_integer(v);
}

/* --- Float conversion --- */

/* CRuby: VALUE rb_float_new(double d) */
mrb_value rb_float_new(double d) {
    return mrb_float_value(konpeito_mrb_state, d);
}

/* CRuby: double rb_num2dbl(VALUE v) */
double rb_num2dbl(mrb_value v) {
    return mrb_as_float(konpeito_mrb_state, v);
}

/* --- String functions --- */

/* CRuby: VALUE rb_str_new(const char *ptr, long len) */
mrb_value rb_str_new(const char *ptr, long len) {
    return mrb_str_new(konpeito_mrb_state, ptr, (mrb_int)len);
}

/* CRuby: VALUE rb_utf8_str_new(const char *ptr, long len) */
/* mruby doesn't distinguish encodings */
mrb_value rb_utf8_str_new(const char *ptr, long len) {
    return mrb_str_new(konpeito_mrb_state, ptr, (mrb_int)len);
}

/* CRuby: VALUE rb_str_new_cstr(const char *ptr) */
mrb_value rb_str_new_cstr(const char *ptr) {
    return mrb_str_new_cstr(konpeito_mrb_state, ptr);
}

/* CRuby: VALUE rb_str_dup(VALUE str) */
mrb_value rb_str_dup(mrb_value str) {
    return mrb_str_dup(konpeito_mrb_state, str);
}

/* CRuby: VALUE rb_str_hash(VALUE str) */
mrb_value rb_str_hash(mrb_value str) {
    /* Use mrb_funcall to call str.hash */
    return mrb_funcall(konpeito_mrb_state, str, "hash", 0);
}

/* CRuby: VALUE rb_str_concat(VALUE str1, VALUE str2) - mutating append */
mrb_value rb_str_concat(mrb_value str1, mrb_value str2) {
    mrb_str_concat(konpeito_mrb_state, str1, str2);
    return str1;
}

/* CRuby: VALUE rb_str_buf_new(long capa) */
mrb_value rb_str_buf_new(long capa) {
    return mrb_str_new_capa(konpeito_mrb_state, (mrb_int)capa);
}

/* CRuby: VALUE rb_str_cat(VALUE str, const char *ptr, long len) */
mrb_value rb_str_cat(mrb_value str, const char *ptr, long len) {
    return mrb_str_cat(konpeito_mrb_state, str, ptr, (mrb_int)len);
}

/* CRuby: VALUE rb_str_buf_append(VALUE str, VALUE str2) */
mrb_value rb_str_buf_append(mrb_value str, mrb_value str2) {
    mrb_str_concat(konpeito_mrb_state, str, str2);
    return str;
}

/* CRuby: VALUE rb_str_length(VALUE str) */
mrb_value rb_str_length(mrb_value str) {
    return mrb_funcall(konpeito_mrb_state, str, "length", 0);
}

/* CRuby: VALUE rb_str_equal(VALUE str1, VALUE str2) */
mrb_value rb_str_equal(mrb_value str1, mrb_value str2) {
    return mrb_funcall(konpeito_mrb_state, str1, "==", 1, str2);
}

/* CRuby: char *rb_string_value_cstr(volatile VALUE *ptr) */
const char *rb_string_value_cstr(mrb_value *ptr) {
    return mrb_str_to_cstr(konpeito_mrb_state, *ptr);
}

/* --- Symbol functions --- */

/* CRuby: VALUE rb_id2sym(ID id) */
mrb_value rb_id2sym(mrb_sym id) {
    return mrb_symbol_value(id);
}

/* CRuby: VALUE rb_sym2str(VALUE sym) */
mrb_value rb_sym2str(mrb_value sym) {
    mrb_sym id = mrb_symbol(sym);
    return mrb_sym_str(konpeito_mrb_state, id);
}

/* --- Regexp --- */

/* CRuby: VALUE rb_reg_new_str(VALUE str, int options) */
mrb_value rb_reg_new_str(mrb_value str, int64_t options) {
    /* Use mrb_funcall to call Regexp.new(str, options) */
    mrb_value regexp_class = mrb_obj_value(mrb_class_get(konpeito_mrb_state, "Regexp"));
    mrb_value opts = mrb_fixnum_value((mrb_int)options);
    return mrb_funcall(konpeito_mrb_state, regexp_class, "new", 2, str, opts);
}

/* --- Array functions --- */

/* CRuby: VALUE rb_ary_new_capa(long capa) */
mrb_value rb_ary_new_capa(int64_t capa) {
    return mrb_ary_new_capa(konpeito_mrb_state, (mrb_int)capa);
}

/* CRuby: VALUE rb_ary_push(VALUE ary, VALUE item) */
mrb_value rb_ary_push(mrb_value ary, mrb_value item) {
    mrb_ary_push(konpeito_mrb_state, ary, item);
    return ary;
}

/* CRuby: VALUE rb_ary_entry(VALUE ary, long offset) */
mrb_value rb_ary_entry(mrb_value ary, int64_t offset) {
    return mrb_ary_ref(konpeito_mrb_state, ary, (mrb_int)offset);
}

/* CRuby: long rb_array_len(VALUE ary) */
int64_t rb_array_len(mrb_value ary) {
    return (int64_t)RARRAY_LEN(ary);
}

/* CRuby: void rb_ary_store(VALUE ary, long idx, VALUE val) */
void rb_ary_store(mrb_value ary, int64_t idx, mrb_value val) {
    mrb_ary_set(konpeito_mrb_state, ary, (mrb_int)idx, val);
}

/* CRuby: VALUE rb_ary_new(void) */
mrb_value rb_ary_new(void) {
    return mrb_ary_new(konpeito_mrb_state);
}

/* CRuby: VALUE rb_ary_new_from_values(long n, const VALUE *elts) */
mrb_value rb_ary_new_from_values(int64_t n, const mrb_value *elts) {
    return mrb_ary_new_from_values(konpeito_mrb_state, (mrb_int)n, elts);
}

/* CRuby: VALUE rb_ary_subseq(VALUE ary, long beg, long len) */
mrb_value rb_ary_subseq(mrb_value ary, int64_t beg, int64_t len) {
    return mrb_ary_subseq(konpeito_mrb_state, ary, (mrb_int)beg, (mrb_int)len);
}

/* CRuby: VALUE rb_ary_concat(VALUE ary1, VALUE ary2) */
mrb_value rb_ary_concat(mrb_value ary1, mrb_value ary2) {
    mrb_ary_concat(konpeito_mrb_state, ary1, ary2);
    return ary1;
}

/* CRuby: VALUE rb_apply(VALUE recv, ID mid, VALUE args) */
mrb_value rb_apply(mrb_value recv, mrb_sym mid, mrb_value args) {
    mrb_int argc = RARRAY_LEN(args);
    const mrb_value *argv = RARRAY_PTR(args);
    return mrb_funcall_argv(konpeito_mrb_state, recv, mid, argc, argv);
}

/* CRuby: VALUE rb_ary_unshift(VALUE ary, VALUE item) */
mrb_value rb_ary_unshift(mrb_value ary, mrb_value item) {
    return mrb_ary_unshift(konpeito_mrb_state, ary, item);
}

/* CRuby: VALUE rb_ary_delete(VALUE ary, VALUE item) */
mrb_value rb_ary_delete(mrb_value ary, mrb_value item) {
    return mrb_funcall(konpeito_mrb_state, ary, "delete", 1, item);
}

/* CRuby: VALUE rb_ary_delete_at(VALUE ary, long pos) */
mrb_value rb_ary_delete_at(mrb_value ary, int64_t pos) {
    mrb_value idx = mrb_fixnum_value((mrb_int)pos);
    return mrb_funcall(konpeito_mrb_state, ary, "delete_at", 1, idx);
}

/* --- Hash functions --- */

/* CRuby: VALUE rb_hash_new(void) */
mrb_value rb_hash_new(void) {
    return mrb_hash_new(konpeito_mrb_state);
}

/* CRuby: VALUE rb_hash_aset(VALUE hash, VALUE key, VALUE val) */
mrb_value rb_hash_aset(mrb_value hash, mrb_value key, mrb_value val) {
    mrb_hash_set(konpeito_mrb_state, hash, key, val);
    return val;
}

/* CRuby: VALUE rb_hash_lookup2(VALUE hash, VALUE key, VALUE def) */
mrb_value rb_hash_lookup2(mrb_value hash, mrb_value key, mrb_value def_val) {
    mrb_value result = mrb_hash_get(konpeito_mrb_state, hash, key);
    if (mrb_nil_p(result)) {
        /* Check if key actually exists with nil value */
        mrb_value exists = mrb_hash_key_p(konpeito_mrb_state, hash, key);
        if (!mrb_test(exists)) {
            return def_val;
        }
    }
    return result;
}

/* --- Class / Module definition --- */

/* CRuby: VALUE rb_define_class(const char *name, VALUE super) */
mrb_value rb_define_class(const char *name, mrb_value super) {
    struct RClass *super_cls = mrb_class_ptr(super);
    struct RClass *cls = mrb_define_class(konpeito_mrb_state, name, super_cls);
    return mrb_obj_value(cls);
}

/* CRuby: VALUE rb_define_class_under(VALUE outer, const char *name, VALUE super) */
mrb_value rb_define_class_under(mrb_value outer, const char *name, mrb_value super) {
    struct RClass *outer_mod = mrb_class_ptr(outer);
    struct RClass *super_cls = mrb_class_ptr(super);
    struct RClass *cls = mrb_define_class_under(konpeito_mrb_state, outer_mod, name, super_cls);
    return mrb_obj_value(cls);
}

/* CRuby: void rb_define_method(VALUE klass, const char *name, VALUE (*func)(...), int argc) */
void rb_define_method(mrb_value klass, const char *name, void *func, int argc) {
    struct RClass *cls = mrb_class_ptr(klass);
    /* Convert CRuby arity to mruby MRB_ARGS */
    mrb_aspec aspec;
    if (argc == -1) {
        aspec = MRB_ARGS_ANY();
    } else if (argc == 0) {
        aspec = MRB_ARGS_NONE();
    } else {
        aspec = MRB_ARGS_REQ(argc);
    }
    mrb_define_method(konpeito_mrb_state, cls, name, (mrb_func_t)func, aspec);
}

/* CRuby: void rb_define_singleton_method(VALUE obj, const char *name, VALUE (*func)(...), int argc) */
void rb_define_singleton_method(mrb_value obj, const char *name, void *func, int argc) {
    struct RClass *cls = mrb_class_ptr(obj);
    mrb_aspec aspec;
    if (argc == -1) {
        aspec = MRB_ARGS_ANY();
    } else if (argc == 0) {
        aspec = MRB_ARGS_NONE();
    } else {
        aspec = MRB_ARGS_REQ(argc);
    }
    mrb_define_class_method(konpeito_mrb_state, cls, name, (mrb_func_t)func, aspec);
}

/* --- Instance variables --- */

/* CRuby: VALUE rb_ivar_get(VALUE obj, ID id) */
mrb_value rb_ivar_get(mrb_value obj, mrb_sym id) {
    return mrb_iv_get(konpeito_mrb_state, obj, id);
}

/* CRuby: VALUE rb_ivar_set(VALUE obj, ID id, VALUE val) */
mrb_value rb_ivar_set(mrb_value obj, mrb_sym id, mrb_value val) {
    mrb_iv_set(konpeito_mrb_state, obj, id, val);
    return val;
}

/* --- Class variables --- */

/* CRuby: VALUE rb_cvar_get(VALUE klass, ID id) */
mrb_value rb_cvar_get(mrb_value klass, mrb_sym id) {
    return mrb_cv_get(konpeito_mrb_state, klass, id);
}

/* CRuby: void rb_cvar_set(VALUE klass, ID id, VALUE val) */
void rb_cvar_set(mrb_value klass, mrb_sym id, mrb_value val) {
    mrb_cv_set(konpeito_mrb_state, klass, id, val);
}

/* --- Object class --- */

/* CRuby: VALUE rb_obj_class(VALUE obj) */
mrb_value rb_obj_class(mrb_value obj) {
    struct RClass *cls = mrb_obj_class(konpeito_mrb_state, obj);
    return mrb_obj_value(cls);
}

/* --- Block / Yield --- */

/* CRuby: VALUE rb_yield(VALUE val) */
mrb_value rb_yield(mrb_value val) {
    mrb_value block = konpeito_get_block();
    if (mrb_nil_p(block)) {
        mrb_raise(konpeito_mrb_state, E_RUNTIME_ERROR, "no block given (yield)");
        return mrb_nil_value();
    }
    return mrb_funcall(konpeito_mrb_state, block, "call", 1, val);
}

/* CRuby: VALUE rb_yield_values2(int argc, const VALUE *argv) */
mrb_value rb_yield_values2(int argc, const mrb_value *argv) {
    mrb_value block = konpeito_get_block();
    if (mrb_nil_p(block)) {
        mrb_raise(konpeito_mrb_state, E_RUNTIME_ERROR, "no block given (yield)");
        return mrb_nil_value();
    }
    mrb_sym call_sym = mrb_intern_cstr(konpeito_mrb_state, "call");
    return mrb_funcall_argv(konpeito_mrb_state, block, call_sym, argc, argv);
}

/* CRuby: int rb_block_given_p(void) */
int rb_block_given_p(void) {
    mrb_value block = konpeito_get_block();
    return !mrb_nil_p(block);
}

/* CRuby: VALUE rb_block_proc(void) */
mrb_value rb_block_proc(void) {
    return konpeito_get_block();
}

/* ================================================================
 * rb_block_call / rb_proc_new callback adapter
 *
 * CRuby callbacks have signature:
 *   VALUE func(VALUE yielded_arg, VALUE data2, int argc, VALUE *argv)
 *
 * mruby cfunc procs have signature:
 *   mrb_value func(mrb_state *mrb, mrb_value self)
 *
 * We bridge the gap using mrb_proc_new_cfunc_with_env() which stores
 * the original callback pointer and data in the proc's environment.
 * ================================================================ */

typedef mrb_value (*cruby_block_callback_t)(mrb_value, mrb_value, int, const mrb_value*);

/* Adapter: called as mruby cfunc, delegates to CRuby-style callback */
static mrb_value konpeito_cfunc_adapter(mrb_state *mrb, mrb_value self) {
    mrb_value cb_ptr_val = mrb_proc_cfunc_env_get(mrb, 0);
    mrb_value data = mrb_proc_cfunc_env_get(mrb, 1);
    void *cb_ptr = mrb_cptr(cb_ptr_val);
    cruby_block_callback_t cb = (cruby_block_callback_t)cb_ptr;

    mrb_value *argv;
    mrb_int argc;
    mrb_get_args(mrb, "*", &argv, &argc);

    mrb_value yielded = (argc > 0) ? argv[0] : mrb_nil_value();
    return cb(yielded, data, (int)argc, argv);
}

/* CRuby: VALUE rb_block_call(VALUE obj, ID mid, int argc, const VALUE *argv,
 *                            rb_block_call_func_t proc, VALUE data2) */
mrb_value rb_block_call(mrb_value obj, mrb_sym mid, int argc, const mrb_value *argv,
                        void *proc, mrb_value data2) {
    if (!proc) {
        return mrb_funcall_argv(konpeito_mrb_state, obj, mid, argc, argv);
    }

    /* Create a proc that wraps the CRuby callback via environment */
    mrb_value env[2];
    env[0] = mrb_cptr_value(konpeito_mrb_state, proc);
    env[1] = data2;
    struct RProc *block_proc = mrb_proc_new_cfunc_with_env(
        konpeito_mrb_state, konpeito_cfunc_adapter, 2, env);
    mrb_value block_val = mrb_obj_value(block_proc);

    return mrb_funcall_with_block(konpeito_mrb_state, obj, mid, argc, argv, block_val);
}

/* CRuby: VALUE rb_block_call_kw(...) */
mrb_value rb_block_call_kw(mrb_value obj, mrb_sym mid, int argc, const mrb_value *argv,
                           void *proc, mrb_value data2, int kw_splat) {
    (void)kw_splat;
    return rb_block_call(obj, mid, argc, argv, proc, data2);
}

/* --- Proc --- */

/* CRuby: VALUE rb_proc_new(rb_block_call_func_t func, VALUE val) */
mrb_value rb_proc_new(void *func, mrb_value val) {
    /* Use mrb_proc_new_cfunc_with_env to store callback + data in proc env.
     * The adapter konpeito_cfunc_adapter reads them back when called. */
    mrb_value env[2];
    env[0] = mrb_cptr_value(konpeito_mrb_state, func);
    env[1] = val;
    struct RProc *proc = mrb_proc_new_cfunc_with_env(
        konpeito_mrb_state, konpeito_cfunc_adapter, 2, env);
    return mrb_obj_value(proc);
}

/* CRuby: VALUE rb_proc_call(VALUE proc, VALUE args) */
mrb_value rb_proc_call(mrb_value proc, mrb_value args) {
    mrb_int argc = RARRAY_LEN(args);
    const mrb_value *argv = RARRAY_PTR(args);
    return mrb_funcall_argv(konpeito_mrb_state, proc, mrb_intern_cstr(konpeito_mrb_state, "call"), argc, argv);
}

/* --- Fiber --- */

/* CRuby: VALUE rb_fiber_new(rb_block_call_func_t func, VALUE obj) */
mrb_value rb_fiber_new(void *func, mrb_value obj) {
    /* Create a proc via env-based adapter (same as rb_proc_new),
     * then create a Fiber from it. */
    mrb_value env[2];
    env[0] = mrb_cptr_value(konpeito_mrb_state, func);
    env[1] = obj;
    struct RProc *proc = mrb_proc_new_cfunc_with_env(
        konpeito_mrb_state, konpeito_cfunc_adapter, 2, env);
    mrb_value proc_val = mrb_obj_value(proc);

    /* Fiber.new(&proc) */
    mrb_value fiber_class = mrb_obj_value(mrb_class_get(konpeito_mrb_state, "Fiber"));
    mrb_sym new_sym = mrb_intern_cstr(konpeito_mrb_state, "new");
    return mrb_funcall_with_block(konpeito_mrb_state, fiber_class, new_sym,
                                  0, NULL, proc_val);
}

/* CRuby: VALUE rb_fiber_resume(VALUE fiber, int argc, const VALUE *argv) */
mrb_value rb_fiber_resume(mrb_value fiber, int argc, const mrb_value *argv) {
    mrb_sym resume_sym = mrb_intern_cstr(konpeito_mrb_state, "resume");
    return mrb_funcall_argv(konpeito_mrb_state, fiber, resume_sym, argc, argv);
}

/* CRuby: VALUE rb_fiber_yield(int argc, const VALUE *argv) */
mrb_value rb_fiber_yield(int argc, const mrb_value *argv) {
    mrb_value fiber_class = mrb_obj_value(mrb_class_get(konpeito_mrb_state, "Fiber"));
    mrb_sym yield_sym = mrb_intern_cstr(konpeito_mrb_state, "yield");
    return mrb_funcall_argv(konpeito_mrb_state, fiber_class, yield_sym, argc, argv);
}

/* CRuby: VALUE rb_fiber_current(void) */
mrb_value rb_fiber_current(void) {
    mrb_value fiber_class = mrb_obj_value(mrb_class_get(konpeito_mrb_state, "Fiber"));
    return mrb_funcall(konpeito_mrb_state, fiber_class, "current", 0);
}

/* CRuby: VALUE rb_fiber_alive_p(VALUE fiber) */
mrb_value rb_fiber_alive_p(mrb_value fiber) {
    return mrb_funcall(konpeito_mrb_state, fiber, "alive?", 0);
}

/* --- Thread (stubs — mruby is single-threaded) --- */

mrb_value rb_thread_create(void *func, void *arg) {
    (void)func;
    (void)arg;
    mrb_raise(konpeito_mrb_state, E_RUNTIME_ERROR, "Thread is not supported in mruby target");
    return mrb_nil_value();
}

mrb_value rb_thread_current(void) {
    mrb_raise(konpeito_mrb_state, E_RUNTIME_ERROR, "Thread is not supported in mruby target");
    return mrb_nil_value();
}

mrb_value rb_mutex_new(void) {
    mrb_raise(konpeito_mrb_state, E_RUNTIME_ERROR, "Mutex is not supported in mruby target");
    return mrb_nil_value();
}

mrb_value rb_mutex_lock(mrb_value mutex) {
    (void)mutex;
    mrb_raise(konpeito_mrb_state, E_RUNTIME_ERROR, "Mutex is not supported in mruby target");
    return mrb_nil_value();
}

mrb_value rb_mutex_unlock(mrb_value mutex) {
    (void)mutex;
    mrb_raise(konpeito_mrb_state, E_RUNTIME_ERROR, "Mutex is not supported in mruby target");
    return mrb_nil_value();
}

/* --- Exception handling --- */

/* Stack-based rescue/ensure adapters for proper nesting support.
 * CRuby callbacks have signature VALUE(*)(VALUE) while mruby has
 * mrb_value(*)(mrb_state*, mrb_value). We use a stack since
 * begin/rescue blocks can be nested. */

typedef mrb_value (*konpeito_callback_fn)(mrb_state *, mrb_value);

#define KONPEITO_MAX_RESCUE_STACK 32

/* Rescue stack */
static struct {
    konpeito_callback_fn body;
    mrb_value data1;
    konpeito_callback_fn handler;
    mrb_value data2;
} rescue_stack[KONPEITO_MAX_RESCUE_STACK];
static int rescue_depth = 0;

static mrb_value rescue_body_wrapper(mrb_state *mrb, mrb_value data) {
    (void)data;
    int idx = rescue_depth - 1;
    return rescue_stack[idx].body(mrb, rescue_stack[idx].data1);
}

static mrb_value rescue_handler_wrapper(mrb_state *mrb, mrb_value data) {
    (void)data;
    int idx = rescue_depth - 1;
    return rescue_stack[idx].handler(mrb, rescue_stack[idx].data2);
}

/* CRuby: VALUE rb_rescue2(VALUE (*body)(VALUE), VALUE data1,
 *                         VALUE (*handler)(VALUE, VALUE), VALUE data2, ...) */
mrb_value rb_rescue2(void *body, mrb_value data1, void *handler, mrb_value data2, ...) {
    if (rescue_depth >= KONPEITO_MAX_RESCUE_STACK) {
        mrb_raise(konpeito_mrb_state, E_RUNTIME_ERROR, "rescue nesting too deep");
        return mrb_nil_value();
    }
    rescue_stack[rescue_depth].body = (konpeito_callback_fn)body;
    rescue_stack[rescue_depth].data1 = data1;
    rescue_stack[rescue_depth].handler = (konpeito_callback_fn)handler;
    rescue_stack[rescue_depth].data2 = data2;
    rescue_depth++;
    mrb_value result = mrb_rescue(konpeito_mrb_state,
                                   rescue_body_wrapper, mrb_nil_value(),
                                   rescue_handler_wrapper, mrb_nil_value());
    rescue_depth--;
    return result;
}

/* Ensure stack */
static struct {
    konpeito_callback_fn body;
    mrb_value data1;
    konpeito_callback_fn cleanup;
    mrb_value data2;
} ensure_stack[KONPEITO_MAX_RESCUE_STACK];
static int ensure_depth = 0;

static mrb_value ensure_body_wrapper(mrb_state *mrb, mrb_value data) {
    (void)data;
    int idx = ensure_depth - 1;
    return ensure_stack[idx].body(mrb, ensure_stack[idx].data1);
}

static mrb_value ensure_cleanup_wrapper(mrb_state *mrb, mrb_value data) {
    (void)data;
    int idx = ensure_depth - 1;
    return ensure_stack[idx].cleanup(mrb, ensure_stack[idx].data2);
}

/* CRuby: VALUE rb_ensure(VALUE (*body)(VALUE), VALUE data1,
 *                        VALUE (*ensure_fn)(VALUE), VALUE data2) */
mrb_value rb_ensure(void *body, mrb_value data1, void *cleanup, mrb_value data2) {
    if (ensure_depth >= KONPEITO_MAX_RESCUE_STACK) {
        mrb_raise(konpeito_mrb_state, E_RUNTIME_ERROR, "ensure nesting too deep");
        return mrb_nil_value();
    }
    ensure_stack[ensure_depth].body = (konpeito_callback_fn)body;
    ensure_stack[ensure_depth].data1 = data1;
    ensure_stack[ensure_depth].cleanup = (konpeito_callback_fn)cleanup;
    ensure_stack[ensure_depth].data2 = data2;
    ensure_depth++;
    mrb_value result = mrb_ensure(konpeito_mrb_state,
                                   ensure_body_wrapper, mrb_nil_value(),
                                   ensure_cleanup_wrapper, mrb_nil_value());
    ensure_depth--;
    return result;
}

/* CRuby: VALUE rb_protect(VALUE (*func)(VALUE), VALUE arg, int *state) */
mrb_value rb_protect(void *func, mrb_value arg, int *state) {
    /* mruby doesn't have rb_protect directly. Use mrb_rescue as approximation. */
    typedef mrb_value (*protect_fn)(mrb_state *, mrb_value);
    protect_fn fn = (protect_fn)func;
    mrb_bool error;
    mrb_value result = mrb_protect(konpeito_mrb_state, (mrb_func_t)fn, arg, &error);
    if (state) *state = error ? 1 : 0;
    return result;
}

/* CRuby: VALUE rb_errinfo(void) */
mrb_value rb_errinfo(void) {
    if (konpeito_mrb_state->exc) {
        return mrb_obj_value(konpeito_mrb_state->exc);
    }
    return mrb_nil_value();
}

/* CRuby: void rb_set_errinfo(VALUE err) */
void rb_set_errinfo(mrb_value err) {
    if (mrb_nil_p(err)) {
        konpeito_mrb_state->exc = NULL;
    } else {
        konpeito_mrb_state->exc = mrb_obj_ptr(err);
    }
}

/* CRuby: void rb_jump_tag(int state) */
void rb_jump_tag(int state) {
    (void)state;
    /* In mruby, there's no direct equivalent. Raise a runtime error. */
    mrb_raise(konpeito_mrb_state, E_RUNTIME_ERROR, "rb_jump_tag called");
}

/* CRuby: void rb_raise(VALUE exc_class, const char *fmt, ...) */
void rb_raise(mrb_value exc_class, const char *fmt, ...) {
    char buf[1024];
    va_list args;
    va_start(args, fmt);
    vsnprintf(buf, sizeof(buf), fmt, args);
    va_end(args);
    struct RClass *cls = mrb_class_ptr(exc_class);
    mrb_raise(konpeito_mrb_state, cls, buf);
}

/* --- Exception class globals --- */
/* In CRuby these are extern VALUE globals. In mruby we provide them
 * as variables initialized at startup. */

mrb_value rb_eStandardError;
mrb_value rb_eRuntimeError;
mrb_value rb_eArgError;  /* CRuby name for ArgumentError */

/* --- Object class global --- */
mrb_value rb_cObject;

/* --- Core class globals --- */
mrb_value rb_cInteger;
mrb_value rb_cFloat;
mrb_value rb_cString;
mrb_value rb_cSymbol;
mrb_value rb_cArray;
mrb_value rb_cHash;
mrb_value rb_cNilClass;
mrb_value rb_cTrueClass;
mrb_value rb_cFalseClass;

/* Thread/Mutex/Queue class globals (stubs) */
mrb_value rb_cThread;
mrb_value rb_cMutex;
mrb_value rb_cQueue;

/* --- Constant access --- */

/* CRuby: VALUE rb_const_get(VALUE module, ID name) */
mrb_value rb_const_get(mrb_value module, mrb_sym name) {
    return mrb_const_get(konpeito_mrb_state, module, name);
}

/* CRuby: void rb_const_set(VALUE module, ID name, VALUE value) */
void rb_const_set(mrb_value module, mrb_sym name, mrb_value value) {
    mrb_const_set(konpeito_mrb_state, module, name, value);
}

/* --- Range --- */

/* CRuby: VALUE rb_range_new(VALUE beg, VALUE end, int exclude_end) */
mrb_value rb_range_new(mrb_value beg, mrb_value end, int exclude_end) {
    return mrb_range_new(konpeito_mrb_state, beg, end, (mrb_bool)exclude_end);
}

/* --- Global variables --- */

/* CRuby: VALUE rb_gv_get(const char *name) */
mrb_value rb_gv_get(const char *name) {
    mrb_sym sym = mrb_intern_cstr(konpeito_mrb_state, name);
    return mrb_gv_get(konpeito_mrb_state, sym);
}

/* CRuby: VALUE rb_gv_set(const char *name, VALUE val) */
mrb_value rb_gv_set(const char *name, mrb_value val) {
    mrb_sym sym = mrb_intern_cstr(konpeito_mrb_state, name);
    mrb_gv_set(konpeito_mrb_state, sym, val);
    return val;
}

/* --- Super call --- */

/* CRuby: VALUE rb_call_super(int argc, const VALUE *argv) */
mrb_value rb_call_super(int argc, const mrb_value *argv) {
    /* mruby doesn't expose a C API for super calls from cfuncs.
     * The Konpeito compiler handles super by directly calling the parent
     * class method by its mangled name. This stub is a fallback. */
    (void)argc;
    (void)argv;
    mrb_raise(konpeito_mrb_state, E_RUNTIME_ERROR,
              "super call from C function is not supported in mruby target");
    return mrb_nil_value();
}

/* --- Type checking --- */

/* CRuby: VALUE rb_obj_is_kind_of(VALUE obj, VALUE klass) */
mrb_value rb_obj_is_kind_of(mrb_value obj, mrb_value klass) {
    struct RClass *cls = mrb_class_ptr(klass);
    mrb_bool result = mrb_obj_is_kind_of(konpeito_mrb_state, obj, cls);
    return result ? mrb_true_value() : mrb_false_value();
}

/* CRuby: VALUE rb_path2class(const char *path) */
mrb_value rb_path2class(const char *path) {
    struct RClass *cls = mrb_class_get(konpeito_mrb_state, path);
    return mrb_obj_value(cls);
}

/* --- Require (stub) --- */

/* CRuby: void rb_require(const char *feature) */
void rb_require(const char *feature) {
    /* mruby doesn't support dynamic require — all code is compiled in.
     * This is a no-op for stdlib requires. */
    (void)feature;
}

/* --- GC marking --- */

/* CRuby: void rb_gc_mark(VALUE obj) */
void rb_gc_mark(mrb_value obj) {
    mrb_gc_mark_value(konpeito_mrb_state, obj);
}

/* ================================================================
 * Initialization function — called from main() after mrb_open()
 * Sets up all the global class/exception variables.
 * ================================================================ */

void konpeito_mruby_init_globals(void) {
    mrb_state *mrb = konpeito_mrb_state;
    if (!mrb) return;

    /* Exception classes */
    rb_eStandardError = mrb_obj_value(E_STANDARD_ERROR);
    rb_eRuntimeError  = mrb_obj_value(E_RUNTIME_ERROR);
    rb_eArgError      = mrb_obj_value(E_ARGUMENT_ERROR);

    /* Object class */
    rb_cObject = mrb_obj_value(mrb->object_class);

    /* Core classes */
    rb_cInteger   = mrb_obj_value(mrb_class_get(mrb, "Integer"));
    rb_cFloat     = mrb_obj_value(mrb_class_get(mrb, "Float"));
    rb_cString    = mrb_obj_value(mrb_class_get(mrb, "String"));
    rb_cSymbol    = mrb_obj_value(mrb_class_get(mrb, "Symbol"));
    rb_cArray     = mrb_obj_value(mrb_class_get(mrb, "Array"));
    rb_cHash      = mrb_obj_value(mrb_class_get(mrb, "Hash"));
    rb_cNilClass  = mrb_obj_value(mrb_class_get(mrb, "NilClass"));
    rb_cTrueClass = mrb_obj_value(mrb_class_get(mrb, "TrueClass"));
    rb_cFalseClass = mrb_obj_value(mrb_class_get(mrb, "FalseClass"));

    /* Thread/Mutex/Queue stubs */
    rb_cThread = mrb_nil_value();
    rb_cMutex  = mrb_nil_value();
    rb_cQueue  = mrb_nil_value();
}

/* ================================================================
 * Additional mruby-specific helpers (konpeito_mrb_* prefix)
 * Used by the MRubyBackend-generated init code.
 * ================================================================ */

/* Type checking helpers */
int konpeito_mrb_test(mrb_value v)       { return mrb_test(v) ? 1 : 0; }
int konpeito_mrb_nil_p(mrb_value v)      { return mrb_nil_p(v) ? 1 : 0; }
int konpeito_mrb_fixnum_p(mrb_value v)   { return mrb_fixnum_p(v) ? 1 : 0; }
int konpeito_mrb_float_p(mrb_value v)    { return mrb_float_p(v) ? 1 : 0; }
int konpeito_mrb_string_p(mrb_value v)   { return mrb_string_p(v) ? 1 : 0; }
int konpeito_mrb_symbol_p(mrb_value v)   { return mrb_symbol_p(v) ? 1 : 0; }
int konpeito_mrb_array_p(mrb_value v)    { return mrb_array_p(v) ? 1 : 0; }
int konpeito_mrb_hash_p(mrb_value v)     { return mrb_hash_p(v) ? 1 : 0; }

/* Value construction helpers */
mrb_value konpeito_mrb_fixnum_value(mrb_int i) { return mrb_fixnum_value(i); }
mrb_int   konpeito_mrb_integer(mrb_value v)    { return mrb_integer(v); }

/* Exception class accessors */
struct RClass *konpeito_mrb_e_runtime_error(mrb_state *mrb)  { return E_RUNTIME_ERROR; }
struct RClass *konpeito_mrb_e_argument_error(mrb_state *mrb) { return E_ARGUMENT_ERROR; }
struct RClass *konpeito_mrb_e_type_error(mrb_state *mrb)     { return E_TYPE_ERROR; }
struct RClass *konpeito_mrb_e_name_error(mrb_state *mrb)     { return E_NAME_ERROR; }
struct RClass *konpeito_mrb_e_index_error(mrb_state *mrb)    { return E_INDEX_ERROR; }
struct RClass *konpeito_mrb_e_range_error(mrb_state *mrb)    { return E_RANGE_ERROR; }
struct RClass *konpeito_mrb_e_standard_error(mrb_state *mrb) { return E_STANDARD_ERROR; }

/* Core class accessors */
struct RClass *konpeito_mrb_object_class(mrb_state *mrb)  { return mrb->object_class; }
struct RClass *konpeito_mrb_class_class(mrb_state *mrb)   { return mrb->class_class; }
struct RClass *konpeito_mrb_string_class(mrb_state *mrb)  { return mrb_class_get(mrb, "String"); }
struct RClass *konpeito_mrb_integer_class(mrb_state *mrb) { return mrb_class_get(mrb, "Integer"); }
struct RClass *konpeito_mrb_float_class(mrb_state *mrb)   { return mrb_class_get(mrb, "Float"); }
struct RClass *konpeito_mrb_array_class(mrb_state *mrb)   { return mrb_class_get(mrb, "Array"); }
struct RClass *konpeito_mrb_hash_class(mrb_state *mrb)    { return mrb_class_get(mrb, "Hash"); }
struct RClass *konpeito_mrb_symbol_class(mrb_state *mrb)  { return mrb_class_get(mrb, "Symbol"); }
struct RClass *konpeito_mrb_true_class(mrb_state *mrb)    { return mrb_class_get(mrb, "TrueClass"); }
struct RClass *konpeito_mrb_false_class(mrb_state *mrb)   { return mrb_class_get(mrb, "FalseClass"); }
struct RClass *konpeito_mrb_nil_class(mrb_state *mrb)     { return mrb_class_get(mrb, "NilClass"); }

/* RClass <-> mrb_value conversion */
mrb_value konpeito_mrb_obj_value(struct RClass *cls) { return mrb_obj_value(cls); }

/* Array length helper */
mrb_int konpeito_mrb_ary_len(mrb_state *mrb, mrb_value ary) {
    (void)mrb;
    return RARRAY_LEN(ary);
}

/* String C-string helper */
const char *konpeito_mrb_str_to_cstr(mrb_state *mrb, mrb_value str) {
    return mrb_str_to_cstr(mrb, str);
}

/* Data pointer access */
void *konpeito_mrb_data_ptr(mrb_value obj) { return DATA_PTR(obj); }

void konpeito_mrb_data_init(mrb_value obj, void *ptr, const mrb_data_type *type) {
    DATA_PTR(obj) = ptr;
    DATA_TYPE(obj) = type;
}

/* mrb_top_self wrapper */
mrb_value konpeito_mrb_top_self(mrb_state *mrb) { return mrb_top_self(mrb); }
