# KUI Theme System — NativeArray color palette + auto-ID

module KUITheme
  @c: NativeArray[Integer, 32]
end

module KUIState
  @ids: NativeArray[Integer, 4]
end

module KUITextBuf
  @b: NativeArray[Integer, 2048]
  @s: NativeArray[Integer, 24]
end
