# @cfunc demo - libm functions
class LibM
  %a{cfunc: "sin"}  def self.sin: (Float) -> Float

  %a{cfunc: "cos"}  def self.cos: (Float) -> Float

  %a{cfunc: "sqrt"}  def self.sqrt: (Float) -> Float
end

module TopLevel
  def test_cfunc: () -> Float
end
